import { renderOutreachMessage } from "@/lib/utils/message";
import { DEFAULT_MESSAGE_TEMPLATE } from "@/lib/constants/message";
import type { Database } from "@/lib/db/types";

type ProspectInsert = Database["public"]["Tables"]["prospects"]["Insert"];

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function daysFromNow(days: number) {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
}

function message(firstName: string | null, username: string) {
  return renderOutreachMessage(DEFAULT_MESSAGE_TEMPLATE, { firstName, username });
}

export type SampleProspect = ProspectInsert & { instagram_username: string };

export function buildSampleProspects(): SampleProspect[] {
  return [
    {
      instagram_username: "maya.chen.aerial",
      display_name: "Maya Chen Aerial",
      first_name: "Maya",
      profile_url: "https://www.instagram.com/maya.chen.aerial/",
      bio: "FAA Part 107 drone photographer. Real estate and commercial aerials across central Texas.",
      follower_count: 4200,
      following_count: 890,
      location_text: "Austin, TX",
      language: "en",
      category: "Drone photographers / drone operators doing paid work",
      fit_score: 92,
      fit_label: "strong_fit",
      qualification_reason:
        "Paid drone operator focused on real estate aerials. Solo business, English, United States, follower count in range.",
      qualified: true,
      already_following: false,
      already_contacted: false,
      message_text: message("Maya", "maya.chen.aerial"),
      status: "review",
      notes: "Strong first example for the review queue.",
      source: "home_feed",
      instagram_post_url: "https://www.instagram.com/p/sampleaerial01/",
      instagram_post_thumbnail_url: "/samples/post-aerial.svg",
      discovered_at: hoursAgo(3),
      is_sample: true,
    },
    {
      instagram_username: "chrisalvarez.re",
      display_name: "Chris Alvarez",
      first_name: "Chris",
      profile_url: "https://www.instagram.com/chrisalvarez.re/",
      bio: "Real estate photographer serving Denver and Boulder. HDR, twilight, and aerial add-ons.",
      follower_count: 8900,
      following_count: 640,
      location_text: "Denver, CO",
      language: "en",
      category: "Real estate photographers",
      fit_score: 88,
      fit_label: "strong_fit",
      qualification_reason:
        "Real estate photographer delivering listing media for agents. Solo operator in the preferred follower range.",
      qualified: true,
      already_following: false,
      already_contacted: false,
      message_text: message("Chris", "chrisalvarez.re"),
      status: "approved",
      source: "home_feed",
      discovered_at: hoursAgo(30),
      approved_at: hoursAgo(20),
      is_sample: true,
    },
    {
      instagram_username: "northlinemedia",
      display_name: "Northline Media",
      first_name: null,
      profile_url: "https://www.instagram.com/northlinemedia/",
      bio: "Listing media for realtors and builders. Photo, video, and aerial.",
      follower_count: 15200,
      following_count: 410,
      location_text: "Phoenix, AZ",
      language: "en",
      category: "Real estate media companies",
      fit_score: 85,
      fit_label: "strong_fit",
      qualification_reason:
        "Small real estate media company. No confident first name, so the message uses the Instagram username.",
      qualified: true,
      already_following: false,
      already_contacted: true,
      message_text: message(null, "northlinemedia"),
      status: "contacted",
      source: "home_feed",
      discovered_at: hoursAgo(24 * 5),
      approved_at: hoursAgo(24 * 4),
      contacted_at: hoursAgo(24 * 3),
      is_sample: true,
    },
    {
      instagram_username: "jordanhale.video",
      display_name: "Jordan Hale",
      first_name: "Jordan",
      profile_url: "https://www.instagram.com/jordanhale.video/",
      bio: "Commercial and real estate video. Small crew for listing films and brand spots.",
      follower_count: 2100,
      following_count: 980,
      location_text: "Nashville, TN",
      language: "en",
      category: "Videographers doing commercial or real estate work",
      fit_score: 71,
      fit_label: "possible_fit",
      qualification_reason:
        "Commercial videographer with some real estate work. Possible fit; confirm they deliver client media themselves.",
      qualified: true,
      already_following: false,
      already_contacted: false,
      message_text: message("Jordan", "jordanhale.video"),
      status: "review",
      source: "home_feed",
      discovered_at: hoursAgo(6),
      is_sample: true,
    },
    {
      instagram_username: "lenaortiz.photo",
      display_name: "Lena Ortiz",
      first_name: "Lena",
      profile_url: "https://www.instagram.com/lenaortiz.photo/",
      bio: "Miami real estate photo and twilight. Working with agents across South Florida.",
      follower_count: 6700,
      following_count: 520,
      location_text: "Miami, FL",
      language: "en",
      category: "Real estate photographers",
      fit_score: 90,
      fit_label: "strong_fit",
      qualification_reason: "Real estate photographer with a clear client workflow and a reply already recorded.",
      qualified: true,
      already_following: false,
      already_contacted: true,
      message_text: message("Lena", "lenaortiz.photo"),
      status: "replied",
      notes: "Asked what ShootPortal replaces in a typical delivery stack.",
      source: "home_feed",
      instagram_post_url: "https://www.instagram.com/p/samplelisting01/",
      instagram_post_thumbnail_url: "/samples/post-listing.svg",
      discovered_at: hoursAgo(24 * 6),
      approved_at: hoursAgo(24 * 5),
      contacted_at: hoursAgo(24 * 4),
      replied_at: hoursAgo(26),
      is_sample: true,
    },
    {
      instagram_username: "pixelandpine",
      display_name: "Pixel & Pine",
      first_name: null,
      profile_url: "https://www.instagram.com/pixelandpine/",
      bio: "Photo and video studio for local businesses and a handful of real estate clients.",
      follower_count: 980,
      following_count: 300,
      location_text: "Portland, OR",
      language: "en",
      category: "Small teams",
      fit_score: 64,
      fit_label: "possible_fit",
      qualification_reason:
        "Small team doing some real estate work, but the account also covers general commercial clients.",
      qualified: true,
      already_following: false,
      already_contacted: false,
      message_text: message(null, "pixelandpine"),
      status: "qualified",
      source: "home_feed",
      discovered_at: hoursAgo(28),
      is_sample: true,
    },
    {
      instagram_username: "skylinereels",
      display_name: "Skyline Reels",
      first_name: null,
      profile_url: "https://www.instagram.com/skylinereels/",
      bio: "Listing films and property videos for brokerages in DFW.",
      follower_count: 22100,
      following_count: 700,
      location_text: "Dallas, TX",
      language: "en",
      category: "Videographers doing commercial or real estate work",
      fit_score: 86,
      fit_label: "strong_fit",
      qualification_reason: "Property video studio booking listing work for brokerages. Demo is already recorded.",
      qualified: true,
      already_following: false,
      already_contacted: true,
      message_text: message(null, "skylinereels"),
      status: "demo_booked",
      source: "home_feed",
      discovered_at: hoursAgo(24 * 8),
      approved_at: hoursAgo(24 * 7),
      contacted_at: hoursAgo(24 * 6),
      replied_at: hoursAgo(24 * 2),
      demo_booked_at: hoursAgo(5),
      is_sample: true,
    },
    {
      instagram_username: "dronememesdaily",
      display_name: "Drone Memes Daily",
      first_name: null,
      profile_url: "https://www.instagram.com/dronememesdaily/",
      bio: "Daily drone memes and crash clips. Not a business.",
      follower_count: 89000,
      following_count: 120,
      location_text: null,
      language: "en",
      category: "Meme page",
      fit_score: 12,
      fit_label: "skip",
      qualification_reason: "Meme page. No evidence of paid client work.",
      qualified: false,
      already_following: false,
      already_contacted: false,
      message_text: message(null, "dronememesdaily"),
      status: "disqualified",
      source: "home_feed",
      discovered_at: hoursAgo(24 * 2),
      is_sample: true,
    },
    {
      instagram_username: "apexaerialpro",
      display_name: "Apex Aerial Productions",
      first_name: null,
      profile_url: "https://www.instagram.com/apexaerialpro/",
      bio: "Full-service aerial production for film, broadcast, and global brands.",
      follower_count: 180000,
      following_count: 250,
      location_text: "Los Angeles, CA",
      language: "en",
      category: "Large production company",
      fit_score: 22,
      fit_label: "skip",
      qualification_reason: "Large production company, outside the solo and small-team focus.",
      qualified: false,
      already_following: false,
      already_contacted: false,
      message_text: message(null, "apexaerialpro"),
      status: "disqualified",
      source: "home_feed",
      discovered_at: hoursAgo(24 * 3),
      is_sample: true,
    },
    {
      instagram_username: "samfliesdrones",
      display_name: "Sam Whitaker",
      first_name: "Sam",
      profile_url: "https://www.instagram.com/samfliesdrones/",
      bio: "Weekend flyer. Sharing flights and sunsets.",
      follower_count: 320,
      following_count: 410,
      location_text: "Columbus, OH",
      language: "en",
      category: "Hobby drone",
      fit_score: 18,
      fit_label: "skip",
      qualification_reason: "Hobby-only account below the follower minimum. No paid work mentioned.",
      qualified: false,
      already_following: false,
      already_contacted: false,
      message_text: message("Sam", "samfliesdrones"),
      status: "skipped",
      source: "home_feed",
      discovered_at: hoursAgo(40),
      is_sample: true,
    },
    {
      instagram_username: "rileynguyen.re",
      display_name: "Riley Nguyen",
      first_name: "Riley",
      profile_url: "https://www.instagram.com/rileynguyen.re/",
      bio: "Real estate and architectural photography. Listing days, twilight, and floor plans.",
      follower_count: 5400,
      following_count: 360,
      location_text: null,
      language: "en",
      category: "Real estate photographers",
      fit_score: 78,
      fit_label: "strong_fit",
      qualification_reason:
        "Real estate photographer. Location could not be verified, so the profile was not disqualified.",
      qualified: true,
      already_following: false,
      already_contacted: false,
      message_text: message("Riley", "rileynguyen.re"),
      status: "review",
      source: "home_feed",
      discovered_at: hoursAgo(2),
      is_sample: true,
    },
    {
      instagram_username: "harborcomedia",
      display_name: "Harbor & Co",
      first_name: null,
      profile_url: "https://www.instagram.com/harborcomedia/",
      bio: "Boutique media team for real estate teams and small builders in the Pacific Northwest.",
      follower_count: 11300,
      following_count: 480,
      location_text: "Seattle, WA",
      language: "en",
      category: "Small teams",
      fit_score: 74,
      fit_label: "possible_fit",
      qualification_reason: "Small media team serving real estate clients. A follow-up is due.",
      qualified: true,
      already_following: false,
      already_contacted: true,
      message_text: message(null, "harborcomedia"),
      status: "follow_up",
      notes: "No reply after the first message.",
      source: "home_feed",
      discovered_at: hoursAgo(24 * 9),
      approved_at: hoursAgo(24 * 8),
      contacted_at: hoursAgo(24 * 7),
      is_sample: true,
    },
  ];
}

export function sampleActivities(username: string) {
  const now = Date.now();
  const at = (hours: number) => new Date(now - hours * 60 * 60 * 1000).toISOString();
  const events: Record<string, { event_type: string; description: string; created_at: string }[]> = {
    "maya.chen.aerial": [
      {
        event_type: "prospect_discovered",
        description: "Discovered @maya.chen.aerial from the home feed.",
        created_at: at(3),
      },
      {
        event_type: "prospect_qualified",
        description: "Qualified @maya.chen.aerial as a strong fit.",
        created_at: at(2.8),
      },
    ],
    "chrisalvarez.re": [
      {
        event_type: "prospect_discovered",
        description: "Discovered @chrisalvarez.re from the home feed.",
        created_at: at(30),
      },
      {
        event_type: "prospect_approved",
        description: "Approved @chrisalvarez.re.",
        created_at: at(20),
      },
    ],
    northlinemedia: [
      {
        event_type: "message_sent",
        description: "Message recorded for @northlinemedia.",
        created_at: at(24 * 3),
      },
    ],
    "lenaortiz.photo": [
      {
        event_type: "message_sent",
        description: "Message recorded for @lenaortiz.photo.",
        created_at: at(24 * 4),
      },
      {
        event_type: "reply_detected",
        description: "Reply recorded from @lenaortiz.photo.",
        created_at: at(26),
      },
    ],
    skylinereels: [
      {
        event_type: "demo_booked",
        description: "Demo booked with @skylinereels.",
        created_at: at(5),
      },
    ],
    samfliesdrones: [
      {
        event_type: "prospect_skipped",
        description: "Skipped @samfliesdrones.",
        created_at: at(39),
      },
    ],
    harborcomedia: [
      {
        event_type: "follow_up_created",
        description: "Follow-up created for @harborcomedia.",
        created_at: at(24 * 6),
      },
    ],
  };

  return (events[username] ?? []).map((event) => ({
    ...event,
    metadata: { sample: true },
  }));
}

export function sampleFollowUps() {
  return [
    {
      username: "harborcomedia",
      due_at: daysFromNow(1),
      status: "pending" as const,
      notes: "No reply after the first message. Check in about media delivery.",
    },
    {
      username: "skylinereels",
      due_at: hoursAgo(5),
      status: "pending" as const,
      notes: "Demo is on the calendar. Confirm the listing workflow they use today.",
    },
  ];
}
